name: mwvent_Spleef
version: 1.7.0
api:
<<<<<<< HEAD
api:
- 1.12.0
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
=======
- 1.0.0
- 2.0.0
>>>>>>> f43753211e3e8b5db5512187c1eb637d926774eb
main: mcg76\game\spleef\SpleefPlugIn
author: minecraftgenius76
description: minecraftgenius76(mwvent customised) Minigame Spleef 
commands:
 spleef:
  description: "Start minecraftgenius76 Minigame Spleef"
  permission: mcg76.spleef.command
permissions:
 mcg76.spleef.command:
  description: "mcg76.spleef"
  default: true
